realtime_back.py: fix string to int conversion
We'll often get a wiops value of 0.00000 or so as wiop in
fio now, but since this is a string and we use int("0.00000"), it
will barf:

ValueError: invalid literal for int() with base 10: '0.00000'

Fix this and use float() to cast the value down to '0.0' which,
and so accomplishes the same goal as the cast to int.

Signed-off-by: Luis Chamberlain <mcgrof@kernel.org>